[build]
command = "npm run build"
publish = ".next"

[functions]
directory = "netlify/functions"


[[services]]
internal_port = 8000
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 8000

[http_service]
  internal_port = 8080  # This matches the port your app listens on.
